###
# LDM
###
ldm:
  # restart: always
  image: unidata/ldm:latest
  container_name: ldm
  volumes:
    # change defaults to your liking
    - ./etc/:/home/ldm/etc/
    - ./data/:/home/ldm/var/data/
    - ./logs/:/home/ldm/var/logs/
  ports:
    - "388:388"
